FIRESTORE_COLLECTION_PLANTS = 'plants'
FIRESTORE_COLLECTION_DISEASES = 'diseases'
FIRESTORE_COLLECTION_USERS = 'users'
FIRESTORE_COLLECTION_ARTICLES = 'articles'
FIRESTORE_COLLECTION_MY_PLANTS = 'my_plants'
FIRESTORE_COLLECTION_PLANT_CATEGORIES='plant_categories'

FIRESTORE_DOCUMENT_METADATA = 'metadata'
