class_names = [
    "Apple___Apple_scab",
    "Apple___Black_rot",
    "Apple___Cedar_apple_rust",
    "Apple___healthy",
    "Blueberry___healthy",
    "Cherry_(including_sour)___Powdery_mildew_embun_tepung",
    "Cherry_(including_sour)___healthy",
    "Corn_(maize)___Gray_leaf_spot_gls",
    "Corn_(maize)___Common_rust",
    "Corn_(maize)___Northern_Leaf_Blight_nclb",
    "Corn_(maize)___healthy",
    "Grape___Black_rot",
    "Grape___Esca_Black_Measles",
    "Grape___Isariopsis_Leaf_Spot",
    "Grape___healthy",
    "Orange___Citrus_greening_hlb",
    "Peach___Bacterial_spot",
    "Peach___healthy",
    "Pepper,_bell___Bacterial_spot",
    "Pepper,_bell___healthy",
    "Potato___Early_blight",
    "Potato___Late_blight",
    "Potato___healthy",
    "Raspberry___healthy",
    "Soybean___healthy",
    "Squash___Embun_tepung_labu",
    "Strawberry___Leaf_scorch",
    "Strawberry___healthy",
    "Tomato___Bacterial_spot",
    "Tomato___Early_blight",
    "Tomato___Late_blight",
    "Tomato___Leaf_Mold",
    "Tomato___Septoria_leaf_spot",
    "Tomato___Spider_mites",
    "Tomato___Target_Spot",
    "Tomato___Penyakit_keriting_kuning_tomat",
    "Tomato___Tomato_mosaic_virus",
    "Tomato___healthy",
]

plant_translate = {
    "Apple": "apel",
    "Blueberry": "blueberry",
    "Cherry including sour": "ceri",
    "Corn maize": "jagung",
    "Grape": "anggur",
    "Orange": "jeruk",
    "Peach": "persik",
    "Pepper, bell": "cabai",
    "Potato": "kentang",
    "Raspberry": "raspberi",
    "Soybean": "kedelai",
    "Squash": "labu",
    "Strawberry": "stroberi",
    "Tomato": "tomat",
}
